#!/usr/bin/env python3
"""Write the five recipes awaiting the owner's publication decision as one
readable document (§13ew). The texts are read from the seed files, so the
document cannot drift from the data: after any correction, run it again.

  python3 scripts/export-approval.py > docs/attribution/rc82-five-for-approval.md
"""
import json, re, sys

CODES = ['mordant-print-paste', 'dye-print-paste', 'dye-mordant-print-paste',
         'pastel-binder-oat', 'pastel-binder-gum']

R = {x['code']: x for x in json.load(open('seed/recipes.json', encoding='utf-8'))['recipes']}
S = {x['code']: x for x in json.load(open('seed/substances.json', encoding='utf-8'))['substances']}
SRC = {x['code']: x for x in json.load(open('seed/sources.json', encoding='utf-8'))['sources']}
VER = re.search(r"VERSION = '([^']+)'", open('version.js').read()).group(1)
roles = {m.group(1): {'bg': m.group(2), 'en': m.group(3)} for m in re.finditer(
    r"V\('ingredient_role',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)'", open('vocab.js', encoding='utf-8').read())}

UNIT = {'bg': {'g': 'г', 'ml': 'мл', 'drop': 'капки'}, 'en': {'g': 'g', 'ml': 'ml', 'drop': 'drops'}}
H = {'bg': dict(ing='Съставки', steps='Стъпки', notes='Бележки', src='Източници', none='няма посочен източник',
                role='роля', qty='количество', choice='избор'),
     'en': dict(ing='Ingredients', steps='Steps', notes='Notes', src='Sources', none='no source given',
                role='role', qty='quantity', choice='choice')}

def num(v, L):
    s = '%g' % v
    return s.replace('.', ',') if L == 'bg' else s

def qty(i, L):
    if i.get('quantity') is None:
        return '—'
    if i.get('basis') == 'ratio_to_dyestuff':          # a proportion, not an amount
        return f"× {num(i['quantity'], L)}"
    return f"{num(i['quantity'], L)} {UNIT[L].get(i.get('unit'), i.get('unit') or '')}"

def option(o, L, unit):
    name = S[o['substanceId'].split(':', 1)[1]]['name'][L] if 'substanceId' in o else o.get('recipeId', '?')
    lo, hi = o.get('qtyMin'), o.get('qtyMax')
    if lo is None:
        return name
    rng = num(lo, L) if lo == hi else f'{num(lo, L)}–{num(hi, L)}'
    return f"{name} ({rng} {UNIT[L].get(unit, unit or '')})"

out = [f'# Five recipes for approval ({VER})', '',
       'Generated by `scripts/export-approval.py` from the seed files of this build — the texts below ARE the',
       'data, not a copy of it. None of the five carries a `distributable` value; each waits for the owner.',
       'Figures are exactly as stored. „—" means the amount is in the note or on the chosen option; „× n" is a',
       'proportion that scales with the first line, not an amount.', '',
       'For each recipe: approve for publication, keep unpublished, or correct. A correction is made in the',
       'JSON and this file is written again.', '']
for code in CODES:
    r = R[code]
    state = 'not set (read as true)' if 'distributable' not in r else str(r['distributable']).lower()
    out += ['---', '', f'## `{code}`', '', f'distributable: **{state}**', '']
    for L in ('bg', 'en'):
        h = H[L]
        out += [f"### {L.upper()} — {r['name'][L]}", '', f"**{h['ing']}**", '',
                f"| {h['role']} | {h['qty']} | {h['choice']} | |", '|---|---|---|---|']
        for i in r['ingredients']:
            ch = ', '.join(option(o, L, i.get('unit')) for o in i.get('options', [])) or '—'
            note = (i.get('note') or {}).get(L, '').replace('|', '\\|')
            out.append(f"| {roles.get(i['roleCode'], {}).get(L, i['roleCode'])} | {qty(i, L)} | {ch} | {note} |")
        out += ['', f"**{h['steps']}**", '']
        out += [f"{n}. {s['text'][L]}" for n, s in enumerate(r['steps'], 1)]
        out += ['', f"**{h['notes']}**", ''] + r['notes'][L].split('\n')
        srcs = [f"{SRC[c]['name'][L]} — {SRC[c]['author'][L]}" for c in r.get('sourceCodes', [])]
        out += ['', f"**{h['src']}:** " + ('; '.join(srcs) if srcs else f"_{h['none']}_"), '']
sys.stdout.write('\n'.join(out) + '\n')
